#################
#
# This is an example Docker file for Weaviate with all OpenAI modules enabled
# You can, but don't have to set `OPENAI_APIKEY` because it can also be set at runtime
#
# Find the latest version here: https://weaviate.io/developers/weaviate/installation/docker-compose
#
#################
---
version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.23.9
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - 8070:8080
    restart: always
    volumes:
      - ~/data/weaviate:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-openai,qna-openai'
      CLUSTER_HOSTNAME: 'openai-weaviate-cluster'
      DISK_USE_READONLY_PERCENTAGE: 95 # 开发环境磁盘空间控制调高